# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $GITHUB_WORKSPACE

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt install curl
          cd $GITHUB_WORKSPACE
          mkdir $GITHUB_WORKSPACE/homedir
          mkdir $GITHUB_WORKSPACE/auxfiles
          sudo bash ./rploader.sh ext geminilake-7.1.1-42951 add https://raw.githubusercontent.com/pocopico/rp-ext/main/e1000e/rpext-index.json
          sudo bash ./rploader.sh build geminilake-7.1.1-42951
